Update capmonster-api.ts
Isn't necessary, because when we use docker after build I get this error:

node_modules/puppeteer-extra-plugin-recaptcha-capmonster/dist/index.cjs.js:48

                        text: result.data.solution?.gRecaptchaResponse

                                                   ^


SyntaxError: Unexpected token '.'

    at wrapSafe (internal/modules/cjs/loader.js:915:16)

    at Module._compile (internal/modules/cjs/loader.js:963:27)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

    at Module.load (internal/modules/cjs/loader.js:863:32)

    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

    at Module.require (internal/modules/cjs/loader.js:887:19)

    at require (internal/modules/cjs/helpers.js:74:18)

    at Object.<anonymous> (/usr/app/build/src/modules/azul/scrapping.js:70:69)

    at Module._compile (internal/modules/cjs/loader.js:999:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)